### ISSUE TITLE
Terminal.app colour scheme

### ISSUE THREAD

**Issue by fuadsaud** [mimshwright/sublime-eggplant-parm#1]
Hi there! Got to say in love with this colour scheme, so I was thinking: do you have a Terminal.app scheme for it? Have sublime and terminal colours matching would be wonderful.

**Comment by mimshwright** [comment]
Thanks very much. I do not have a terminal.app version. I'd love some help with creating one if you're interested.

**Comment by fuadsaud** [comment]
Hmm, I never did such a colorscheme, but after a couple of minutes I came up with something like this: https://gist.github.com/fuadsaud/5640536

There's a couple of rough edges (like the black colours), but I'm open to suggestions.

**Comment by mimshwright** [comment]
Added it to the repo. thanks again!

Mims H. Wright
Software Developer
@mimshwright
