### ISSUE TITLE
ChocolatApp compatible: removed empty definitions

### ISSUE THREAD

**Issue by michelkaeser** [mimshwright/sublime-eggplant-parm#2]
ChocolatApp can't handle empty <string></string> tags and will fail to start with the theme.

I've stripped them out and now it works great. See http://drops.frontender.ch/UQmO/4bQRHNcN for changed version.

Just if you want to add it to the repo or remove them from your version as well so it's compatible :)

**Comment by mimshwright** [comment]
Hey Michel, Thanks for this. Would you mind doing a pull request for this change?
